### ISSUE TITLE
combining individual transition specific models fit with flexsurv 

### ISSUE THREAD

**Issue by svd09** [chjackson/flexsurv-dev#104]
Hi,
In your earlier version of the flexsurv package, the fmsm function can be used to combine the various transition specific models fit separately for each transition. 
However, in your version 2.0 (new version), the function is not available. I cannot load an older version of your package as I work in a protected TRE that does not allow me to load my own packages. What function / code can I use instead of fmsm

Thanks

**Comment by chjackson** [comment]
`fmsm` should still be there, it was never removed.   What made you conclude it wasn't available?

**Comment by svd09** [comment]
Thanks. I realise that the package loaded in our environment was a very old
version. I have requested that they install the newest version on CRAN.
Normally, they automatically install the newest version, but they somehow
did not do that for flexsurv.
Thanks for the prompt response.

Sincerely,

Dr Salil V Deo MD
Staff Cardiovascular Surgeon
Surgical Services, Louis Stokes Cleveland VAMC
North-east Ohio VA Healthcare
10701 East Boulevard
Cleveland Ohio 44106

Associate Professor,
Department of Surgery
Case School of Medicine
Case Western Reserve University
Cleveland Ohio 44106
