### ISSUE TITLE
Next CRAN release?

### ISSUE THREAD

**Issue by hfrick** [chjackson/flexsurv-dev#133]
Would you be open to doing a CRAN release soon-ish? 

I'm using the dev version of flexsurv for [censored](https://github.com/tidymodels/censored/) for the nice new `predict()` methods by @mattwarkentin. I'm looking to release censored to CRAN soon and would love to be able to depend on a new version of flexsurv! 🙌

**Comment by chjackson** [comment]
Certainly - I'll put a CRAN release together today.   Nothing in particular was holding it up - happy to if it would help to progress the tidymodels ecosystem along.

**Comment by hfrick** [comment]
Fantastic, thank you so much! 💯

**Comment by chjackson** [comment]
OK 2.2 is live on CRAN now.
