### ISSUE TITLE
Vignette for distributions gives wrong transform for location for Generalised Gamma (Prentice)

### ISSUE THREAD

**Issue by heor-robyoung** [chjackson/flexsurv-dev#134]
The distributions vignette gives the following description of the log-mean of the generalised gamma:

![image](https://user-images.githubusercontent.com/32358051/175045997-be1bd3f1-2ffc-4281-80b8-6ac5048f636f.png)

However, the linear predictor is not exponentiated in practice, as mu is unbounded and the distribution list shows that it has identity transform:

![image](https://user-images.githubusercontent.com/32358051/175045774-882dec99-2fef-4fef-8fb8-e19191c2b089.png)

**Comment by chjackson** [comment]
Thanks, fixed in https://github.com/chjackson/flexsurv-dev/commit/d5b414e1b08e49b5f5dd794801c5602e6112d7ec .
