### ISSUE TITLE
Enable `.` in formula

### ISSUE THREAD

**Issue by hfrick** [chjackson/flexsurv-dev#143]
I'd like to be able to use a formula like `Surv(time, event) ~ .` with the `.` specification. I was wondering if it's intentional that this isn't working.

If not: I've poked around and passed the data to the terms function and all tests are passing. Would you be open to a PR for that? 

``` r
library(flexsurv)
#> Loading required package: survival

flexsurvreg(Surv(time, status) ~ ., data = lung, dist = "lognormal")
#> Error in terms.formula(formula): '.' in formula and no 'data' argument
```

<sup>Created on 2022-10-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by chjackson** [comment]
It isn't deliberate - I was just unaware of this feature of formula syntax when I first wrote the package.  It seems to have become more popular in recent years - I guess it's part of a statistics vs machine learning cultural change ("just stick everything in...")!    Happy to accept a PR to put it in.

**Comment by hfrick** [comment]
Great, thanks! I promise it's more deliberate than "just stick everything in..."! 🤓 (I need it to get some tidymodels functionality to run where it's actually "stick everything in that's left at this point".) 

`terms()` interprets the dots as referring "to the remaining variables contained in data" so that's typically the main effects but obviously depends what actually is in `data`.

**Comment by chjackson** [comment]
I meant that, as I understand it, `terms()` interprets `~.` as equivalent to `~ x + y` in a dataset with variables `x` and `y`, when it could have interpreted it as `~ x*y`. Which I think is making a judgement about what a sensible model should be.  I don't mind flexsurv doing this, but I think it should be explicitly stated in the documentation.
