### ISSUE TITLE
partial argument matching

### ISSUE THREAD

**Issue by sebffischer** [chjackson/flexsurv-dev#149]
Your package depends on partial argument matching. Instead of the correct name `length.out` in the function `seq()` you are using `length`

consider the code

```r
old_opts = options(
  warnPartialMatchArgs = TRUE,
  warnPartialMatchAttr = TRUE,
  warnPartialMatchDollar = TRUE
)
seq(length = 10)
```

**Comment by chjackson** [comment]
I think I've removed all the partial matches in `flexsurv` now.  Running `flexsurv`'s tests with these options set also revealed use of partial matching in the `survival` package, which I filed [an issue ](https://github.com/therneau/survival/issues/222) about.  In the meantime, I've forced the calls to `survival::survreg` to be run with these options switched off.   So `flexsurv`'s tests should run cleanly with these options on now.
