### ISSUE TITLE
`standsurv`: contrast time to certain quantiles of events

### ISSUE THREAD

**Issue by hezht3** [chjackson/flexsurv-dev#154]
Hi, thank you for this amazing package. As shown in [this vignette](https://cran.r-project.org/web/packages/flexsurv/vignettes/standsurv.html), `standsurv` function allows contrasts of difference/ratio between exposure groups. I wonder if there's any way to calculate the contrast of time to certain quantiles of events (time ratio/time difference), and derive the standard errors of this contrast using delta method/bootstrapping. Thanks very much!

**Comment by chjackson** [comment]
In general in flexsurv, you can use bootstrapping to get uncertainty for any function of model parameters via passing a user-defined function to `summary()`  - see the section "Custom model summaries" in the vignette.     @mikesweeting did you want to give a more focused answer to this for the easiest way to do this in `standsurv`?

**Comment by mikesweeting** [comment]
Currently standsurv doesn't have `type="quantile"` but I will look to implement it. It should be relatively easy to add.

You can use `summary()` as described by @chjackson but not sure how easy it would be to get standard errors of the contrasts out

**Comment by hezht3** [comment]
Dear Chris and Mike,
Thank you very much for getting back to me and suggestions. Look forward to see this implemented in future release.
Thanks!

**Comment by hezht3** [comment]
Thanks very much for incorporating `quantile` type in `standsurv` function. I will close this issue as it has been resolved.
