### ISSUE TITLE
Calibrating and validating flexsurvspline model

### ISSUE THREAD

**Issue by lgondara** [chjackson/flexsurv-dev#158]
Is there any extension of this package or any other function that someone is aware of for calibrating and validating the flexsurvspline models? Similar to calibrate and validate in rms package for Cox model. Or should we just use the KM based binning approach for calibration? Same for any time-dependent AUC measures for these models.

**Comment by chjackson** [comment]
I am not familiar with this style of modelling, but [SurvMetrics](https://cran.r-project.org/web/packages/SurvMetrics/index.html) might do something like what you want. 

Also flexsurv is supported by the [tidymodels](https://www.tidymodels.org) ecosystem via the [censored](https://censored.tidymodels.org/) package, and I think there are standard tools within that ecosystem for cross-validation.    [https://www.tidymodels.org/start/resampling/](https://www.tidymodels.org/start/resampling/) might be a good place to start, but I have not used these tools.

**Comment by lgondara** [comment]
Thanks for the quick response. I will give these a shot.
