### ISSUE TITLE
export flexsurv:::dists?

### ISSUE THREAD

**Issue by MattWiener** [chjackson/flexsurv-dev#16]
Hi.   Thanks for the extremely useful package.   I've got a use case in which I need to define piecewise distribution functions for flexsurv, based on dynamic input from a user.   So the user might say from time 0 to time 100, I want a gamma distribution, from time 100 to time 200 I want a lognormal distribution, and so on, where any distribution defined in the flexsurv package would be allowed.   I have this working, but in order to get the transformations and inverse transformations for the various components, I currently use the information in `flexsurv:::flexsurv.dists`.   If I want to do this in another package, which I do, I get warnings that I am not supposed to reference non-exported objects.

Is there a different way to get this information that I've overlooked in the documentation?   If not, would it be possible to export `flexsurv.dists`?  Alternately, could I contribute my code for building piecewise functions to `flexsurv`?   I would be happy to proceed in any way that makes sense.

Please let me know what you think.   Thanks!

**Comment by chjackson** [comment]
That sounds reasonable.  I've exported it in the latest commit. The only concern is being obliged to document all exported objects, but I've done an \alias{flexsurv.dists} in help(flexsurvreg) and written a bit about it under the "dist" argument.  This satisfies R CMD check --as-cran now, and I hope it will in the future!

**Comment by MattWiener** [comment]
great, thanks!   I'll look forward to the new version coming out on cran.
