### ISSUE TITLE
Inconsistent standard errors when rescaling continuous covariates

### ISSUE THREAD

**Issue by JoshVeasy** [chjackson/flexsurv-dev#162]
Hi

First off sorry if this a dumb question and I'm missing something obvious. I've been developing models in both flexsurvreg and flexsurvspline that include continuous covariates. Due to the size of the continuous covariate, I have on occasion re scaled it by say dividing by 1000. Whilst the parameter estimates remain consistent (taking into account the change of scale), I have been getting quite different SEs for the parameter estimates and thus in turn different p-values and hence inconsistent results for the significance of said covariate. I have tested this scenario using survreg and this inconsistency does not arise there. I have also tried using both Nelson-Mead and BFGS for the optimization approach and get the same problem.

I am happy to provide some code if needs but the data I am using cannot be shared.

Best,
Josh

**Comment by chjackson** [comment]
SEs for the basic parameters in flexsurv (e.g. log covariate effects) are based on estimates of the Hessian (matrix of second derivatives of the log-likelihood) at the MLE.  That involves numerical differentiation.  For some of the models in flexsurv there are first derivatives available, but none of them have second derivatives.   I think the models in survreg have analytic formulae for the first and second derivatives, so I'd expect the SEs to be more accurate than flexsurv for the same model.  I'd also expect the numerical methods for estimating the Hessian to be more accurate if all the parameters are on a similar scale.

**Comment by chjackson** [comment]
Created new issue to implement analytic second derivatives #170

**Comment by shishir-909** [comment]
@chjackson were the analytic second derivatives implemented for the log normal model? I was working with a dataset where the parameters are on very different scales (see [here](https://stats.stackexchange.com/questions/657281/how-to-convert-the-standard-errors-of-regression-co-efficients-obtained-from-the?noredirect=1#comment1234936_657281)). Based on the huge discrepancy in the standard errors of the estimates between the `survival` package and `flexsurv`, would I be right in assuming that the log normal model still uses numerical methods for estimating the Hessian? (I manually computed the Hessian by calculating the second derivatives and found the same standard errors as the `survival` package, but was wondering why is it different to the standard errors reported by `flexsurv`.)
