### ISSUE TITLE
dbase.survspline does not update knots

### ISSUE THREAD

**Issue by pdmetcalfe** [chjackson/flexsurv-dev#22]
dbase.survspline does not return updated ```knots``` variable

**Comment by chjackson** [comment]
After changing dbase.survspline to return the knots, the first spline example from the vignette throws "Mismatch between knots and points" from splines.cpp.   Had you already worked around this somehow?   

(I don't even remember intending to support vectorising the number of knots, but the documentation in Survspline.Rd says I did!)

**Comment by pdmetcalfe** [comment]
Yes, I was startled by the vectorising over knots, and I have some difficulty seeing a reason to have it.

The C++ code works if either it gets a vector of knots or a matrix (at least according to the tests).  Are you returning knots or knots[ind,, drop=FALSE] from dbase.survspline ?

**Comment by pdmetcalfe** [comment]
Ah.  ```dsurvspline``` trims the ```x``` vector, but does not trim the ```knots``` matrix?

**Comment by chjackson** [comment]
Yes that's it.  I also spotted a || instead of a | in the definition of ind2.   Thanks.

**Comment by chjackson** [comment]
Fixed in da3be82
