### ISSUE TITLE
Add quantile functions to dfns + implement medians in summary.flexsurv

### ISSUE THREAD

**Issue by jrdnmdhl** [chjackson/flexsurv-dev#24]
It would be useful to include the quantile functions (e.g. qweibull, qllogis, etc...) for each distribution in dfns.  Doing so would make it quite simple to extend summary.flexsurvreg to calculate predicted medians.

**Comment by chjackson** [comment]
Yes I agree.   This would need `form.dp` in `custom.R` to add the quantile function if it doesn't exist already.  A generic quantile function could be written using `qgeneric` in the package, which does root-finding based on the CDF.

**Comment by jrdnmdhl** [comment]
Addressed w/ #27.
