### ISSUE TITLE
Missing exports

### ISSUE THREAD

**Issue by jrdnmdhl** [chjackson/flexsurv-dev#28]
Many previously exported functions seem to be missing.  Not sure, but I think this may have been introduced when switching to roxygen2.

Some of the things that are no longer exported:
+ summary.flexsurvreg (generic still works, but can't be called directly)
+ hweibull, Hweibull, and many of the other survival-related functions
+ print.flexsurvreg

**Comment by chjackson** [comment]
I think this is fixed now, probably with eeb1b37c?
