### ISSUE TITLE
Errors when compiling/loading package

### ISSUE THREAD

**Issue by jrdnmdhl** [chjackson/flexsurv-dev#43]
I can't seem to get flexsurv-dev to compile/load properly on OSX or Windows 10.  It does install just fine using `install_github`, but running build and load in Rstudio fails.  It's possible that I have not configured Rcpp to build properly, though I am able to build and load dplyr, as well as compile and run simple c++ snippets without error.

Here's what I get on OSX:

> ==> R CMD INSTALL --no-multiarch --with-keep.source flexsurv-dev
> 
> * installing to library ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library’
> * installing *source* package ‘flexsurv’ ...
> make: Nothing to be done for `all'.
> ** libs
> installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/flexsurv/libs
> ** R
> ** data
> *** moving datasets to lazyload DB
> ** inst
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> Error: package or namespace load failed for ‘flexsurv’ in dyn.load(file, DLLpath = DLLpath, ...):
>  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/flexsurv/libs/flexsurv.so':
>   dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/flexsurv/libs/flexsurv.so, 6): Symbol not found: _flexsurv_basis_matrix
>   Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/flexsurv/libs/flexsurv.so
>   Expected in: flat namespace
>  in /Library/Frameworks/R.framework/Versions/3.4/Resources/library/flexsurv/libs/flexsurv.so
> Error: loading failed
> Execution halted
> ERROR: loading failed
> * removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/flexsurv’
> * restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/flexsurv’
> 
> Exited with status 1.

Here's what I get on Windows 10:

> ==> Rcpp::compileAttributes()
> 
> * Updated src/RcppExports.cpp
> * Updated R/RcppExports.R
> 
> ==> Rcmd.exe INSTALL --no-multiarch --with-keep.source flexsurv-dev-master
> 
> * installing to library 'C:/Program Files/R/R-3.4.1/library'
> * installing *source* package 'flexsurv' ...
> c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
> ** libs
> c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c flexsurv-init.c -o flexsurv-init.o
> c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c genf.cpp -o genf.o
> c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c gengamma.cpp -o gengamma.o
> c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c gompertz.cpp -o gompertz.o
> c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c llogis.cpp -o llogis.o
> c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c special.cpp -o special.o
> c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c splines.cpp -o splines.o
> c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o flexsurv.dll tmp.def RcppExports.o flexsurv-init.o genf.o gengamma.o gompertz.o llogis.o special.o splines.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.1/bin/x64 -lR
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x1c8): undefined reference to `flexsurv_basis_matrix'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x1e0): undefined reference to `flexsurv_basis_vector'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x1f8): undefined reference to `flexsurv_check_genf'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x210): undefined reference to `flexsurv_check_gengamma'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x228): undefined reference to `flexsurv_check_gompertz'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x240): undefined reference to `flexsurv_check_llogis'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x258): undefined reference to `flexsurv_dbasis_matrix'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x270): undefined reference to `flexsurv_dbasis_vector'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x288): undefined reference to `flexsurv_dexph'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x2a0): undefined reference to `flexsurv_dgenf_work'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x2b8): undefined reference to `flexsurv_dgengamma_work'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x2d0): undefined reference to `flexsurv_dgompertz_work'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x2e8): undefined reference to `flexsurv_dllogis_work'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x300): undefined reference to `flexsurv_exph'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x318): undefined reference to `flexsurv_pgenf_work'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x330): undefined reference to `flexsurv_pgengamma_work'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x348): undefined reference to `flexsurv_pgompertz_work'
> flexsurv-init.o:flexsurv-init.c:(.rdata+0x360): undefined reference to `flexsurv_pllogis_work'
> collect2.exe: error: ld returned 1 exit status
> no DLL was created
> ERROR: compilation failed for package 'flexsurv'
> * removing 'C:/Program Files/R/R-3.4.1/library/flexsurv'
> * restoring previous 'C:/Program Files/R/R-3.4.1/library/flexsurv'
> 
> Exited with status 1.
>

**Comment by chjackson** [comment]
Sorry for not getting back to this before.  Did you sort it out?  With random installation problems like this, I usually find that reinstalling all the package dependencies, cleaning the package src and rebuilding helps.  Though in this case there's no mention of functions in dependent packages...  If it's a Rcpp issue, @pdmetcalfe may have a quick answer.

**Comment by pdmetcalfe** [comment]
I have no clue.

**Comment by pdmetcalfe** [comment]
Aha, no, I have a clue.

When you do it in rstudio, it reruns `Rcpp::compileAttributes()`.  Because of changes in how Rcpp names stuff, that which the package is expecting to find as `flexsurv_foo` is now called `_flexsurv_foo`.

Hilarity ensues.

**Comment by chjackson** [comment]
Thanks @jrdnmdhl and @pdmetcalfe  .    Regarding the changes in RcppExports.R, is there any reason the "PACKAGE =" argument to .Call is no longer needed?

**Comment by jrdnmdhl** [comment]
@chjackson Apologies forgot to respond to this.  Not sure why that got removed or what the implications are for its absence.  That file is automatically generated when building the package.

**Comment by chjackson** [comment]
OK - looks like the new routine registration facility (see flexsurv-init.c) means the PACKAGE= argument is no longer required.

**Comment by chjackson** [comment]
I'm wondering whether a dependency should be added on the newest version of Rcpp, in which these names were changed.  I'm thinking this is not required for end users, but only for people wanting to rebuild flexsurv?
