### ISSUE TITLE
Bug in qllogis using lower.tail?

### ISSUE THREAD

**Issue by nsb334** [chjackson/flexsurv-dev#46]
I'm not sure if the lower.tail argument is working for qllogis - see below
Thanks

> packageVersion("flexsurv")
[1] ‘1.1’
> qgengamma(p=c(0.1,0.4,0.6,0.9), Q=1,  lower.tail=TRUE)
[1] 0.1053605 0.5108256 0.9162907 2.3025851
> qgengamma(p=c(0.1,0.4,0.6,0.9), Q=1,  lower.tail=FALSE)
[1] 2.3025851 0.9162907 0.5108256 0.1053605
> qllogis(p=c(0.1,0.4,0.6,0.9),  lower.tail=TRUE)
[1] 0.1111111 0.6666667 1.5000000 9.0000000
> qllogis(p=c(0.1,0.4,0.6,0.9),  lower.tail=FALSE)
[1] 0.1111111 0.6666667 1.5000000 9.0000000

**Comment by chjackson** [comment]
Thanks.  This is now fixed in https://github.com/chjackson/flexsurv-dev/commit/783beaefe171204485341c7fbdbfb27744e34dab.
