### ISSUE TITLE
Could we run Probabilistic sensitivity analysis on Curve fit?

### ISSUE THREAD

**Issue by Calou1234** [chjackson/flexsurv-dev#55]
Dear chjackson,

Thanks for your help to my previous comment.

Now I am struggling with generating probabilistic sensitivity analysis on flexsurvspline (k=2, hazard). Do you have any extension regarding this aspect?
I have managed to generate different multivariate normal distribution and got a matrix of gamma (0 to 3) using the package "MASS". Now How can I calculate the survival function using the new gamma (in my example below called "coef.sample"?

I would like to have as an output: for each time, a percentage of survival following the Spline function dictated for each coef.sample.

`library("flexsurv")
surv.fit <- flexsurvspline(Surv(recyrs, censrec) ~ 1, data = flexsurv::bc, k=2, scale="hazard")
library("MASS")
coef.sample <- MASS::mvrnorm(n = 1000, mu = surv.fit$res.t[, "est"], surv.fit$cov)
ggplot2::ggplot(data.frame(coef.sample), aes_string(x = "shape", y = "scale")) +
  geom_point()`

Best Regards,
Carine

**Comment by Calou1234** [comment]
Thanks a lot for your answer!
Can we do the same with Gompertz or Gen Gamma in flexsurv?

Best Regards,
Carine

Le jeu. 6 sept. 2018 à 12:20, Chris Jackson <notifications@github.com> a
écrit :

**Comment by chjackson** [comment]
Yes, every distribution has a "p" function, pgompertz, pgengamma,...

**Comment by Calou1234** [comment]
Thanks.
Will you write it like that for 5 years and log normal distribution?
plnorm(5, meanlog=coef.sample[5,1], knots=surv.fit$knots[5,2],
lower.tail=FALSE)

Best Regards,
Carine

Le jeu. 6 sept. 2018 à 13:11, Chris Jackson <notifications@github.com> a
écrit :

**Comment by Calou1234** [comment]
Sorry a mistake on my side, the code should be:
plnorm(5, meanlog=coef.sample[,1], knots=surv.fit$knots[,2],
lower.tail=FALSE)

Is it correct?

**Comment by chjackson** [comment]
No, knots are only for spline models. Log normal distributions have mean and SD parameters on the log scale, and no knots.  You should first use flexsurvreg to fit the log normal model. 

I'm closing this issue now, as this isn't really a help forum.  Please take some time to understand the details of the code examples I've given, and consult the help pages for each function you use so you understand what it does, and the necessary arguments.
