### ISSUE TITLE
Does `sim.fmsm` take into account coefficient uncertainty?

### ISSUE THREAD

**Issue by sdaza** [chjackson/flexsurv-dev#80]
Hello, 
Thank you for such a great package. 

I wonder if the `sim.fmsm` function considers the uncertainty of model coefficients and estimates. It seems that `msfit.flexsurvreg` does. 

Thanks

**Comment by chjackson** [comment]
No, `sim.fmsm` simulates a sample from a model with fixed parameters.   To get uncertainty around summaries of the sample, you could wrap `bootci.fmsm` around the function that computes the summary.  See the example in `help(bootci.fmsm)`. This function is available in the GitHub version but not on CRAN yet.

**Comment by sdaza** [comment]
Thanks! Do you know if I can use the output from bootci.fsm as input for the function`sim.fmsm`?

**Comment by chjackson** [comment]
It works like this - as explained in the help page.

```
summfn <- function(x, ...){
    sim <-  sim.fmsm(x, ...) 
 ##  [[ compute the summary you want here. ]] 
}
mod <- flexsurvreg(...)
```

Then 
```
bootci.fmsm(mod, fn=summfn, ) 
```

computes a bootstrap sample or a confidence interval for the summary you want.

**Comment by sdaza** [comment]
Cool, thanks!
