### ISSUE TITLE
activate bash strict mode for CI

### ISSUE THREAD

**Issue by kkmann** [chjackson/flexsurv-dev#86]
I think the current setup does not honestly report the results of R CMD CHECK because you call devtools::test afterwards and Travis does not use bash strict mode by default (i.e. currently 'checks passed' only means that the tests run through, but not the full check).

See also https://github.com/travis-ci/travis-ci/issues/1066

I think a line `- set -e` would be needed but that depends a bit on the intended behaviour.

**Comment by kkmann** [comment]
alternatively, just removing the explicit call to ´devtools::test´ would also do the trick. my understanding is that ´R CMD check´ runs the tests anyhow

https://github.com/chjackson/flexsurv-dev/blob/722389158e87ec02ccc618cea249d8634db0067d/.travis.yml#L12

**Comment by kkmann** [comment]
currently, some of the multicore tests seem to fail. Note that `- Rscript -e 'devtools::test()' ` will not lead to a failed CI build even if there are tests failing, is that intended?

**Comment by kkmann** [comment]
the relevant section in the docs is here: https://docs.travis-ci.com/user/languages/r/#customizing-the-travis-build-steps

**Comment by chjackson** [comment]
Now using github actions instead of travis
